# Generated by Django 5.0.2 on 2024-02-10 10:33

import jsonschemafield.fields
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ("jsonschemafield", "0001_initial"),
    ]

    operations = (
        [
            migrations.CreateModel(
                name="JSONSchemaFieldTestModel",
                fields=[
                    (
                        "id",
                        models.BigAutoField(
                            auto_created=True,
                            primary_key=True,
                            serialize=False,
                            verbose_name="ID",
                        ),
                    ),
                    (
                        "json_field_with_schema",
                        jsonschemafield.fields.JSONSchemaField(default=dict),
                    ),
                ],
            ),
        ]
        if settings.IS_TESTING
        else []
    )  # Only run that migration during tests.
